export const FETCH_FARMING = 'benelux/FETCH_FARMING';
export const FETCHING_FARMING_PENDING = 'benelux/FETCHING_FARMING_PENDING';
export const FETCHING_FARMING_SUCCESS = 'benelux/FETCHING_FARMING_SUCCESS';
export const FETCHING_FARMING_FAILURE = 'benelux/FETCHING_FARMING_FAILURE';
