export const FETCHING_BREATHING_PENDING = 'benelux/FETCHING_BREATHING_PENDING';
export const FETCHING_BREATHING_SUCCESS = 'benelux/FETCHING_BREATHING_SUCCESS';
export const FETCHING_BREATHING_FAILURE = 'benelux/FETCHING_BREATHING_FAILURE';
