export const FETCHING_ALLERGY_PENDING = 'benelux/FETCHING_ALLERGY_PENDING';
export const FETCHING_ALLERGY_SUCCESS = 'benelux/FETCHING_ALLERGY_SUCCESS';
export const FETCHING_ALLERGY_FAILURE = 'benelux/FETCHING_ALLERGY_FAILURE';
